let adminState={isAdmin:false,users:[],categories:[],lessons:[],category:'all',search:'',selectedUser:null,trainingProgress:[]};
let trainingState={categories:[],lessons:[],category:'all',search:'',progress:[]};
function trainingDone(id){return trainingState.progress.some(p=>p.lesson_id===id&&p.status==='completed')}
function trainingProgressRow(id){return trainingState.progress.find(p=>p.lesson_id===id)||null}
function parseTrainingQuiz(raw){if(Array.isArray(raw))return raw; if(!raw)return []; try{const x=JSON.parse(raw); return Array.isArray(x)?x:[]}catch{return []}}
function youtubeEmbedUrl(url){const m=String(url||'').match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|embed\/|shorts\/))([A-Za-z0-9_-]{6,})/); return m?`https://www.youtube.com/embed/${m[1]}?rel=0&modestbranding=1`:''}

document.addEventListener('DOMContentLoaded',()=>{bindAdminUI();refreshAdminAccess();bindTrainingUI();});
document.addEventListener('auth:ready',refreshAdminAccess);
document.addEventListener('cloud:data-ready',()=>{if(adminState.isAdmin){loadAdminUsers();loadAdminLearning();}loadTrainingView();});
function startQuoteRotation(){const q=DEFAULT_DATA.quotes||[];if(!q.length)return;let idx=Math.floor(Math.random()*q.length);renderQuote(idx);window.setInterval(()=>{let n=Math.floor(Math.random()*q.length);if(q.length>1&&n===idx)n=(n+1)%q.length;idx=n;renderQuote(idx)},60000)}
document.addEventListener('DOMContentLoaded',()=>{window.setTimeout(startQuoteRotation,300)});

async function refreshAdminAccess(){
 const client=window.supabaseClient,user=window.currentUser;
 if(!client||!user){setAdminVisibility(false);return;}
 const {data,error}=await client.from('user_roles').select('role').eq('user_id',user.id).maybeSingle();
 adminState.isAdmin=!error&&data?.role==='admin'; setAdminVisibility(adminState.isAdmin);
 if(adminState.isAdmin){loadAdminUsers();loadAdminLearning();}
 loadTrainingView();
}
function setAdminVisibility(ok){
 document.querySelectorAll('.admin-only').forEach(x=>x.hidden=!ok);
 const view=document.getElementById('view-admin');if(view)view.hidden=!ok;
 const training=document.querySelectorAll('[data-view="training"]');training.forEach(x=>x.hidden=false);
 const tv=document.getElementById('view-training');if(tv)tv.hidden=false;
 if(!ok&&typeof activeView!=='undefined'&&activeView==='admin'&&typeof showView==='function')showView('dashboard');
}
function bindAdminUI(){
 document.addEventListener('click',e=>{
  const tab=e.target.closest('[data-admin-tab]');if(tab){document.querySelectorAll('[data-admin-tab]').forEach(x=>x.classList.toggle('active',x===tab));document.querySelectorAll('[data-admin-panel]').forEach(x=>x.classList.toggle('active',x.dataset.adminPanel===tab.dataset.adminTab));if(tab.dataset.adminTab==='learning')loadAdminLearning();if(tab.dataset.adminTab==='users')loadAdminUsers();return;}
  const act=e.target.closest('[data-admin-action]');if(act){handleAdminAction(act.dataset.adminAction,act.dataset.userId||'');return;}
  const cat=e.target.closest('[data-admin-category]');if(cat){adminState.category=cat.dataset.adminCategory;renderAdminLearning();return;}
  const edit=e.target.closest('[data-admin-edit]');if(edit){adminLessonModal(edit.dataset.adminEdit);return;}
  const pub=e.target.closest('[data-admin-publish]');if(pub){toggleLessonPublish(pub.dataset.adminPublish);return;}
  const del=e.target.closest('[data-admin-delete]');if(del){deleteAdminLesson(del.dataset.adminDelete);return;}
  const preview=e.target.closest('[data-admin-preview]');if(preview){previewLesson(preview.dataset.adminPreview);return;}
  const dup=e.target.closest('[data-admin-duplicate]');if(dup){duplicateLesson(dup.dataset.adminDuplicate);return;}
  const tcat=e.target.closest('[data-training-category]');if(tcat){trainingState.category=tcat.dataset.trainingCategory;renderTrainingView();return;}
  const topen=e.target.closest('[data-training-open]');if(topen){openTrainingLesson(topen.dataset.trainingOpen);return;}
 });
 document.getElementById('adminRefreshUsers')?.addEventListener('click',loadAdminUsers);
 document.getElementById('adminRefreshLearning')?.addEventListener('click',loadAdminLearning);
 document.getElementById('adminAddLesson')?.addEventListener('click',()=>adminLessonModal());
 document.getElementById('adminAddCategory')?.addEventListener('click',adminCategoryModal);
 document.getElementById('adminUserSearch')?.addEventListener('input',e=>{adminState.search=e.target.value.toLowerCase();renderAdminUsers();});
 document.getElementById('trainingSearch')?.addEventListener('input',e=>{trainingState.search=e.target.value.toLowerCase();renderTrainingView();});
}
async function handleAdminAction(action,userId){
 if(action==='retry-users')return loadAdminUsers();
 if(action==='refresh-all'){await loadAdminUsers();await loadAdminLearning();return;}
 if(action==='focus-users'){document.querySelector('[data-admin-tab=\"users\"]')?.click();return;}
 if(action==='focus-learning'){document.querySelector('[data-admin-tab=\"learning\"]')?.click();return;}
 if(action==='open-user')return openAdminUser(userId);
 if(action==='role-toggle')return toggleAdminRole(userId);
 if(action==='admin-deposit')return adminBalanceModal(userId,'deposit');
 if(action==='admin-withdrawal')return adminBalanceModal(userId,'withdrawal');
}
async function loadAdminUsers(){
 if(!adminState.isAdmin||!window.supabaseClient)return;
 const body=document.getElementById('adminUsersBody');if(body)body.innerHTML='<tr><td colspan="10">Загрузка…</td></tr>';
 const {data,error}=await window.supabaseClient.rpc('admin_list_users');
 if(error){if(body)body.innerHTML=`<tr><td colspan="11"><div class="admin-error"><b>Не удалось загрузить пользователей</b><span>${escapeHtml(error.message||'Ошибка')}</span><button class="secondary-btn" data-admin-action="retry-users">Повторить</button></div></td></tr>`;return;}
 adminState.users=data||[];renderAdminUsers();renderAdminOverview();
}
function formatAdminMoney(v,currency){const code=currency||'USD';const item=(DEFAULT_DATA.currencies||[]).find(x=>x[0]===code);const symbol=item?item[1]:code;return `${symbol}${new Intl.NumberFormat('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v)||0)}`;}
function renderAdminUsers(){
 const body=document.getElementById('adminUsersBody');if(!body)return;
 const q=adminState.search;const rows=adminState.users.filter(u=>!q||String(u.email||'').toLowerCase().includes(q)||String(u.display_name||'').toLowerCase().includes(q));
 body.innerHTML=rows.map(u=>`<tr><td><div class="admin-user-cell"><div class="admin-avatar">${u.avatar_url?`<img src="${escapeAttr(u.avatar_url)}" alt="">`:escapeHtml((u.display_name||u.email||'U').charAt(0).toUpperCase())}</div><div><b>${escapeHtml(u.display_name||'Без никнейма')}</b><small>${escapeHtml(u.email||'')}</small></div></div></td><td><span class="currency-chip">${escapeHtml(u.currency||'—')}</span></td><td class="admin-balance">${formatAdminMoney(Number(u.current_balance||0),u.currency)}</td><td class="positive">+${formatAdminMoney(Number(u.deposits||0),u.currency)}</td><td class="negative">−${formatAdminMoney(Number(u.withdrawals||0),u.currency)}</td><td>${Number(u.trades_count||0).toLocaleString('ru-RU')}</td><td class="${Number(u.pnl)>0?'positive':Number(u.pnl)<0?'negative':''}">${formatAdminMoney(Number(u.pnl||0),u.currency)}</td><td>${Number(u.win_rate||0).toFixed(1)}%</td><td>${formatAdminDate(u.last_sign_in_at)}</td><td><span class="admin-role ${u.role==='admin'?'is-admin':''}">${u.role==='admin'?'ADMIN':'USER'}</span></td><td><div class="admin-row-actions"><button class="mini-btn" data-admin-action="open-user" data-user-id="${u.id}">Открыть</button>${u.id!==window.currentUser?.id?`<button class="mini-btn" data-admin-action="role-toggle" data-user-id="${u.id}">${u.role==='admin'?'Снять admin':'Сделать admin'}</button>`:''}</div></td></tr>`).join('')||'<tr><td colspan="11">Ничего не найдено.</td></tr>';
}
function renderAdminOverview(){
 const box=document.getElementById('adminOverview');if(!box)return;const u=adminState.users;
 const trades=u.reduce((s,x)=>s+Number(x.trades_count||0),0),active=u.filter(x=>x.last_sign_in_at).length;
 const groups={};u.forEach(x=>{const c=x.currency||'USD';groups[c]=(groups[c]||0)+Number(x.current_balance||0)});
 const balances=Object.entries(groups).map(([c,v])=>formatAdminMoney(v,c)).join(' · ')||'—';
 box.innerHTML=`<div class="admin-stat"><span>Пользователи</span><b>${u.length}</b><small>${active} с историей входов</small></div><div class="admin-stat"><span>Все сделки</span><b>${trades.toLocaleString('ru-RU')}</b><small>по всем аккаунтам</small></div><div class="admin-stat"><span>Валюты</span><b>${Object.keys(groups).length}</b><small>${Object.keys(groups).join(' · ')||'—'}</small></div><div class="admin-stat"><span>Баланс по валютам</span><b>${balances}</b><small>без смешивания разных валют</small></div>`;
}
async function openAdminUser(id){
 const {data,error}=await window.supabaseClient.rpc('admin_user_detail',{target_user:id});if(error){toast(error.message,true);return;}adminState.selectedUser=data;renderAdminUserModal(data);
}
function renderAdminUserModal(d){
 const u=d.user,s=d.summary||{};openModal();document.getElementById('modalContent').innerHTML=`<div class="admin-detail"><div class="admin-detail-head"><div><span class="eyebrow">USER CONTROL</span><h2>${escapeHtml(u.display_name||'Без никнейма')}</h2><p>${escapeHtml(u.email||'')}</p><span class="currency-badge">Валюта счёта: ${escapeHtml(u.currency||'—')}</span></div><span class="admin-role ${u.role==='admin'?'is-admin':''}">${u.role}</span><span class="currency-chip">${escapeHtml(s.currency||u.currency||'USD')}</span></div><div class="admin-detail-kpis"><div><span>Баланс</span><b>${formatAdminMoney(Number(s.current_balance||0),s.currency||u.currency)}</b></div><div><span>Сделки</span><b>${Number(s.trades||0).toLocaleString('ru-RU')}</b></div><div><span>P&amp;L</span><b>${formatAdminMoney(Number(s.pnl||0),s.currency||u.currency)}</b></div><div><span>Win Rate</span><b>${Number(s.win_rate||0).toFixed(1)}%</b></div><div><span>Пополнения</span><b>${formatAdminMoney(Number(s.deposits||0),s.currency||u.currency)}</b></div><div><span>Выводы</span><b>${formatAdminMoney(Number(s.withdrawals||0),s.currency||u.currency)}</b></div></div><div class="admin-detail-actions"><button class="secondary-btn" data-admin-action="admin-deposit" data-user-id="${u.id}">＋ Пополнить</button><button class="secondary-btn" data-admin-action="admin-withdrawal" data-user-id="${u.id}">− Вывести</button></div><div class="admin-detail-section"><h3>Последние сделки</h3><div class="admin-mini-list">${(d.trades||[]).map(t=>`<div><span>${escapeHtml(t.date||'')} ${escapeHtml(String(t.time||'').slice(0,5))}</span><b>${escapeHtml(t.instrument||'')}</b><strong class="${Number(t.pnl)>=0?'positive':'negative'}">${formatAdminMoney(Number(t.pnl||0),s.currency||u.currency)}</strong></div>`).join('')||'<small>Нет сделок</small>'}</div></div><div class="admin-detail-section"><h3>Последние операции</h3><div class="admin-mini-list">${(d.operations||[]).map(o=>`<div><span>${escapeHtml(o.date||'')}</span><b>${o.type==='withdrawal'?'Вывод':'Пополнение'}</b><strong>${o.type==='withdrawal'?'−':'+'}${formatAdminMoney(Number(o.amount||0),o.currency||s.currency||u.currency)}</strong></div>`).join('')||'<small>Нет операций</small>'}</div></div></div>`;
}
async function toggleAdminRole(id){const u=adminState.users.find(x=>x.id===id);if(!u)return;if(!confirm(`${u.role==='admin'?'Снять права администратора у':'Назначить администратором'} ${u.email}?`))return;const {error}=await window.supabaseClient.rpc('admin_set_user_role',{target_user:id,new_role:u.role==='admin'?'user':'admin'});if(error){toast(error.message,true);return;}toast('Роль обновлена');loadAdminUsers();}
function adminBalanceModal(userId,type){
 openSimpleModal(type==='deposit'?'Админ: пополнение':'Админ: вывод','Операция будет записана в баланс выбранного участника.',async f=>{const {error}=await window.supabaseClient.rpc('admin_add_balance_operation',{target_user:userId,op_type:type,op_amount:Number(f.amount),op_note:f.note||'',op_date:f.date||new Date().toISOString().slice(0,10),op_time:f.time||new Date().toTimeString().slice(0,5)});if(error){toast(error.message,true);return;}toast('Операция записана');openAdminUser(userId);loadAdminUsers();},[{name:'amount',label:'Сумма',type:'number',step:'0.01',required:true},{name:'date',label:'Дата',type:'date',value:new Date().toISOString().slice(0,10)},{name:'time',label:'Время',type:'time',value:new Date().toTimeString().slice(0,5)},{name:'note',label:'Комментарий',type:'text',value:''}]);
}
async function loadAdminLearning(){
 if(!adminState.isAdmin||!window.supabaseClient)return;const [c,l]=await Promise.all([window.supabaseClient.from('learning_categories').select('*').order('sort_order'),window.supabaseClient.from('learning_lessons').select('*').order('sort_order')]);if(c.error||l.error){toast((c.error||l.error)?.message||'Ошибка обучения',true);return;}adminState.categories=c.data||[];adminState.lessons=l.data||[];renderAdminLearning();loadTrainingView();
}
function renderAdminLearning(){
 const cats=document.getElementById('adminCategoryList'),lessons=document.getElementById('adminLessons');if(!cats||!lessons)return;
 cats.innerHTML=`<button class="admin-category ${adminState.category==='all'?'active':''}" data-admin-category="all">Все уроки <b>${adminState.lessons.length}</b></button>`+adminState.categories.map(c=>`<button class="admin-category ${adminState.category===c.id?'active':''}" data-admin-category="${c.id}">${escapeHtml(c.title)} <b>${adminState.lessons.filter(l=>l.category_id===c.id).length}</b></button>`).join('');
 const list=adminState.category==='all'?adminState.lessons:adminState.lessons.filter(l=>l.category_id===adminState.category);
 lessons.innerHTML=list.map(l=>`<article class="admin-lesson-row"><div><span class="admin-status ${l.status}">${l.status==='published'?'ОПУБЛИКОВАН':'ЧЕРНОВИК'}</span><h4>${escapeHtml(l.title)}</h4><p>${escapeHtml(l.excerpt||'Без описания')}</p><small>${escapeHtml(l.lesson_type||'article')} · ${escapeHtml(adminState.categories.find(c=>c.id===l.category_id)?.title||'Без категории')}</small></div><div class="admin-row-actions"><button class="secondary-btn" data-admin-preview="${l.id}">Просмотр</button><button class="secondary-btn" data-admin-edit="${l.id}">Изменить</button><button class="ghost-btn" data-admin-duplicate="${l.id}">Копия</button><button class="ghost-btn" data-admin-publish="${l.id}">${l.status==='published'?'Снять':'Опубликовать'}</button><button class="danger-btn" data-admin-delete="${l.id}">Удалить</button></div></article>`).join('')||'<div class="empty-inline">Уроков пока нет.</div>';
}
function adminCategoryModal(id){const c=adminState.categories.find(x=>x.id===id)||{};openSimpleModal(id?'Изменить категорию':'Новая категория','Категории формируют левую навигацию обучения.',async f=>{const row={title:f.title,slug:(f.slug||f.title).toLowerCase().trim().replace(/[^a-z0-9а-яё]+/gi,'-'),description:f.description||'',sort_order:Number(f.sort_order)||0,published:f.published!=='false'};const r=id?await window.supabaseClient.from('learning_categories').update(row).eq('id',id):await window.supabaseClient.from('learning_categories').insert(row);if(r.error){toast(r.error.message,true);return;}toast('Категория сохранена');loadAdminLearning();},[{name:'title',label:'Название',type:'text',value:c.title||'',required:true},{name:'slug',label:'Slug',type:'text',value:c.slug||''},{name:'description',label:'Описание',type:'textarea',value:c.description||''},{name:'sort_order',label:'Порядок',type:'number',value:c.sort_order||0}]);}
function adminLessonModal(id){const l=adminState.lessons.find(x=>x.id===id)||{};openSimpleModal(id?'Изменить урок':'Новый урок','Структура: видео → теория/пост → примеры → практика → тест → конспект.',async f=>{const cat=adminState.categories.find(c=>c.title===f.category_id);const row={title:f.title,slug:(f.slug||f.title).toLowerCase().trim().replace(/[^a-z0-9а-яё]+/gi,'-'),excerpt:f.excerpt||'',lesson_type:f.lesson_type||'article',category_id:cat?.id||null,duration_minutes:f.duration?Number(f.duration):null,status:f.status||'draft',content:{videoUrl:f.videoUrl||'',article:f.article||'',examples:f.examples||'',imageUrl:f.imageUrl||'',practice:f.practice||'',quiz:f.quiz||'',keyTakeaway:f.keyTakeaway||''},created_by:window.currentUser?.id||null};const r=id?await window.supabaseClient.from('learning_lessons').update(row).eq('id',id):await window.supabaseClient.from('learning_lessons').insert(row);if(r.error){toast(r.error.message,true);return;}toast(id?'Урок обновлён':'Урок создан');loadAdminLearning();},[{name:'title',label:'Название',type:'text',value:l.title||'',required:true},{name:'slug',label:'Slug',type:'text',value:l.slug||''},{name:'category_id',label:'Категория',type:'select',options:adminState.categories.map(c=>c.title),value:adminState.categories.find(c=>c.id===l.category_id)?.title||adminState.categories[0]?.title||''},{name:'lesson_type',label:'Тип',type:'select',options:['video','article','post','practice','interactive'],value:l.lesson_type||'article'},{name:'duration',label:'Минуты',type:'number',value:l.duration_minutes||''},{name:'status',label:'Статус',type:'select',options:['draft','published'],value:l.status||'draft'},{name:'excerpt',label:'Краткое описание',type:'textarea',value:l.excerpt||''},{name:'videoUrl',label:'YouTube / видео URL',type:'text',value:l.content?.videoUrl||''},{name:'imageUrl',label:'URL изображения',type:'text',value:l.content?.imageUrl||''},{name:'article',label:'Теория / пост',type:'textarea',value:l.content?.article||''},{name:'examples',label:'Примеры',type:'textarea',value:l.content?.examples||''},{name:'practice',label:'Практика / задание',type:'textarea',value:l.content?.practice||''},{name:'quiz',label:'Тест / вопросы',type:'textarea',value:l.content?.quiz||''},{name:'keyTakeaway',label:'Главный вывод',type:'textarea',value:l.content?.keyTakeaway||''}]);}
async function toggleLessonPublish(id){const l=adminState.lessons.find(x=>x.id===id);if(!l)return;const {error}=await window.supabaseClient.from('learning_lessons').update({status:l.status==='published'?'draft':'published'}).eq('id',id);if(error)toast(error.message,true);else loadAdminLearning();}
async function duplicateLesson(id){const l=adminState.lessons.find(x=>x.id===id);if(!l)return;const row={...l};delete row.id;row.title=`${l.title} — копия`;row.slug=`${l.slug}-copy-${Date.now()}`;row.status='draft';row.created_by=window.currentUser?.id||null;const {error}=await window.supabaseClient.from('learning_lessons').insert(row);if(error)toast(error.message,true);else{toast('Копия создана');loadAdminLearning();}}
async function deleteAdminLesson(id){if(!confirm('Удалить урок?'))return;const {error}=await window.supabaseClient.from('learning_lessons').delete().eq('id',id);if(error)toast(error.message,true);else loadAdminLearning();}
function previewLesson(id){openTrainingLesson(id);}

async function loadTrainingView(){if(!window.supabaseClient||!window.currentUser)return;const [c,l,p]=await Promise.all([window.supabaseClient.from('learning_categories').select('*').eq('published',true).order('sort_order'),window.supabaseClient.from('learning_lessons').select('*').eq('status','published').order('sort_order'),window.supabaseClient.from('learning_progress').select('*').eq('user_id',window.currentUser.id)]);if(c.error||l.error)return;trainingState.categories=c.data||[];trainingState.lessons=l.data||[];trainingState.progress=p.data||[];renderTrainingView();}
function renderTrainingView(){
 const tabs=document.getElementById('trainingCategoryTabs'),grid=document.getElementById('trainingLessonGrid');if(!tabs||!grid)return;
 const allLabel=trainingState.category==='all'?'active':'';
 tabs.innerHTML=`<button class="${allLabel}" data-training-category="all">Все материалы <b>${trainingState.lessons.length}</b></button>`+trainingState.categories.map(c=>`<button class="${trainingState.category===c.id?'active':''}" data-training-category="${c.id}">${escapeHtml(c.title)} <b>${trainingState.lessons.filter(l=>l.category_id===c.id).length}</b></button>`).join('');
 const q=String(trainingState.search||'').trim();let list=trainingState.category==='all'?trainingState.lessons:trainingState.lessons.filter(l=>l.category_id===trainingState.category);
 if(q)list=list.filter(l=>(`${l.title||''} ${l.excerpt||''} ${l.lesson_type||''} ${(l.content?.article||'')}`).toLowerCase().includes(q));
 const doneFor=l=>trainingState.progress.some(p=>p.lesson_id===l.id&&p.status==='completed');
 const feature=document.getElementById('trainingFeature');
 const featured=list[0]||trainingState.lessons[0];
 if(feature){feature.innerHTML=featured?`<div><span class="eyebrow">РЕКОМЕНДОВАННЫЙ МАТЕРИАЛ</span><h3>${escapeHtml(featured.title)}</h3><p>${escapeHtml(featured.excerpt||'Открой материал, изучи теорию и выполни практическое задание.')}</p><div class="feature-meta"><span>${escapeHtml((featured.lesson_type||'article').toUpperCase())}</span><span>${featured.duration_minutes?featured.duration_minutes+' мин':'Материал'}</span><span>${doneFor(featured)?'✓ ПРОЙДЕНО':'НЕ ПРОЙДЕНО'}</span></div><button class="primary-btn" data-training-open="${featured.id}" style="margin-top:14px">Открыть урок →</button></div>`:`<div><span class="eyebrow">БАЗА ЗНАНИЙ</span><h3>Материалы появятся здесь</h3><p>Администратор ещё не опубликовал уроки.</p></div>`;}
 grid.innerHTML=list.map((l,i)=>{const done=doneFor(l),pr=trainingProgressRow(l.id),pct=done?100:Math.min(99,Math.max(0,Number(pr?.progress||0)));return `<article class="training-lesson card training-db-card" data-training-open="${l.id}"><div class="training-thumb thumb-${String.fromCharCode(97+(i%6))}"><span>${String(i+1).padStart(2,'0')}</span><b>${escapeHtml((l.lesson_type||'article').toUpperCase())}</b></div><div class="training-lesson-body"><span class="training-type">${done?'✓ ПРОЙДЕНО':pct?'В ПРОЦЕССЕ':'УРОК'}</span><h4>${escapeHtml(l.title)}</h4><p>${escapeHtml(l.excerpt||'Открыть материал и пройти практику.')}</p><div class="training-card-progress"><i style="width:${pct}%"></i></div><div><span>${l.duration_minutes?l.duration_minutes+' мин':'Материал'}</span><span>•</span><span>${done?'Завершён':pct?`${pct}% · Продолжить`:'Начать урок →'}</span></div></div></article>`}).join('')||'<div class="empty-inline">По этому запросу материалов нет.</div>';
 const rc=document.getElementById('trainingResultCount');if(rc)rc.textContent=`${list.length} ${list.length===1?'урок':list.length<5?'урока':'уроков'}`;
 const roadmap=document.getElementById('trainingRoadmap');if(roadmap)roadmap.innerHTML=trainingState.categories.map((c,i)=>`<button type="button" class="${trainingState.category===c.id?'current':''}" data-training-category="${c.id}"><i>${String(i+1).padStart(2,'0')}</i><span>${escapeHtml(c.title)}</span><small>${trainingState.lessons.filter(l=>l.category_id===c.id).length} уроков</small></button>`).join('');
 const completed=trainingState.progress.filter(x=>x.status==='completed').length,total=trainingState.lessons.length,percent=total?Math.round(completed/total*100):0;const pl=document.getElementById('trainingProgressLabel'),pb=document.getElementById('trainingProgressBar'),pt=document.getElementById('trainingProgressText');if(pl)pl.textContent=percent+'%';if(pb)pb.style.width=percent+'%';if(pt)pt.textContent=`Завершено ${completed} из ${total} уроков.`;
 const activity=[...trainingState.progress].sort((a,b)=>new Date(b.updated_at||b.completed_at||b.started_at||0)-new Date(a.updated_at||a.completed_at||a.started_at||0))[0];const activityLesson=activity?trainingState.lessons.find(l=>l.id===activity.lesson_id):null;const inProgress=trainingState.progress.filter(x=>x.status==='started'&&Number(x.progress||0)<100).sort((a,b)=>Number(b.progress||0)-Number(a.progress||0))[0];const continueLesson=inProgress?trainingState.lessons.find(l=>l.id===inProgress.lesson_id):null;const next=continueLesson||trainingState.lessons.find(l=>!doneFor(l));
 const dash=document.getElementById('trainingProgressDashboard');if(dash){const date=activity?.updated_at?new Date(activity.updated_at).toLocaleDateString('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric'}):'Пока нет активности';const catStats=trainingState.categories.map(c=>{const ls=trainingState.lessons.filter(l=>l.category_id===c.id);const done=ls.filter(doneFor).length;return {title:c.title,done,total:ls.length,p:ls.length?Math.round(done/ls.length*100):0}}).filter(x=>x.total);const topCats=catStats.slice(0,3);dash.innerHTML=`<article class="progress-dashboard-card progress-dashboard-main"><span class="eyebrow">ОБЩИЙ ПРОГРЕСС</span><strong>${percent}%</strong><div class="dashboard-progress-track"><i style="width:${percent}%"></i></div><span>${completed} из ${total} уроков завершено</span></article><article class="progress-dashboard-card"><span class="eyebrow">ПОСЛЕДНЯЯ АКТИВНОСТЬ</span><b>${escapeHtml(activityLesson?.title||'Пока нет активности')}</b><span>${date}</span></article><article class="progress-dashboard-card"><span class="eyebrow">ПРОДОЛЖИТЬ</span><b>${escapeHtml(continueLesson?.title||next?.title||'Маршрут завершён')}</b><span>${continueLesson?Number(inProgress.progress||0)+'% завершено':next?'Следующий урок':'Все уроки пройдены'}</span></article><article class="progress-dashboard-card progress-dashboard-categories"><span class="eyebrow">ПО КАТЕГОРИЯМ</span>${topCats.length?topCats.map(x=>`<div class="category-progress-line"><span>${escapeHtml(x.title)}</span><b>${x.p}%</b><i><em style="width:${x.p}%"></em></i></div>`).join(''):'<span>Категории появятся после публикации уроков.</span>'}</article>`;}
 const nextBox=document.getElementById('trainingNextLesson');if(nextBox)nextBox.innerHTML=next?`<b>${escapeHtml(next.title)}</b><span>${escapeHtml(continueLesson?`Уже начат: ${Number(inProgress.progress||0)}%. Продолжи с этого места.`:(next.excerpt||'Следующий материал в учебном маршруте.'))}</span><button class="secondary-btn" data-training-open="${next.id}" style="margin-top:10px">${continueLesson?'Продолжить →':'Начать урок →'}</button>`:`<b>Маршрут завершён</b><span>Все опубликованные уроки отмечены как пройденные.</span>`;
}
async function openTrainingLesson(id){const l=trainingState.lessons.find(x=>x.id===id)||adminState.lessons.find(x=>x.id===id);if(!l)return;const c=l.content||{};const existing=trainingProgressRow(l.id);if(window.currentUser&&window.supabaseClient&&!existing){await window.supabaseClient.from('learning_progress').upsert({user_id:window.currentUser.id,lesson_id:l.id,status:'started',progress:10,started_at:new Date().toISOString(),updated_at:new Date().toISOString()});await loadTrainingView();}
 const row=trainingProgressRow(l.id)||{};const quiz=parseTrainingQuiz(c.quiz);const embed=youtubeEmbedUrl(c.videoUrl);openModal();document.getElementById('modalContent').innerHTML=`<div class="training-lesson-modal"><div class="lesson-header-row"><span class="eyebrow">${escapeHtml((l.lesson_type||'lesson').toUpperCase())}</span><span class="lesson-progress-pill">${Number(row.progress||0)}%</span></div><h2>${escapeHtml(l.title)}</h2><p class="lesson-excerpt">${escapeHtml(l.excerpt||'')}</p>${embed?`<div class="lesson-video-frame"><iframe src="${embed}" title="Видео урока" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>`:(c.videoUrl?`<div class="lesson-video-link"><a href="${escapeAttr(c.videoUrl)}" target="_blank" rel="noopener">▶ Открыть видео</a></div>`:'')}${c.imageUrl?`<img class="lesson-image" src="${escapeAttr(c.imageUrl)}" alt="">`:''}<div class="lesson-flow"><span>01 Теория</span><span>02 Примеры</span><span>03 Практика</span><span>04 Тест</span><span>05 Конспект</span></div><div class="lesson-block"><h3>Теория</h3><div>${escapeHtml(c.article||'Материал будет добавлен.')}</div></div>${c.examples?`<div class="lesson-block"><h3>Примеры</h3><div>${escapeHtml(c.examples)}</div></div>`:''}<div class="lesson-block"><h3>Практика</h3><div>${escapeHtml(c.practice||'Практическое задание будет добавлено.')}</div></div>${quiz.length?`<div class="lesson-block lesson-quiz"><h3>Проверка знаний</h3>${quiz.map((q,i)=>`<fieldset class="quiz-question"><legend>${i+1}. ${escapeHtml(q.question||'Вопрос')}</legend>${(q.options||[]).map((o,j)=>`<label><input type="radio" name="quiz-${i}" value="${j}"> <span>${escapeHtml(o)}</span></label>`).join('')}</fieldset>`).join('')}<button class="secondary-btn" id="checkQuizBtn">Проверить тест</button><div id="quizResult" class="quiz-result"></div></div>`:''}<div class="lesson-block"><h3>Конспект</h3><textarea id="lessonNotes" class="lesson-notes" placeholder="Коротко запиши, что важно запомнить…">${escapeHtml(row.notes||'')}</textarea></div><div class="lesson-block"><h3>Главный вывод</h3><div>${escapeHtml(c.keyTakeaway||'Сформулируй главный вывод после прохождения урока.')}</div></div><div class="modal-actions"><button class="secondary-btn" id="saveLessonNotesBtn">Сохранить конспект</button><button class="primary-btn" id="completeLessonBtn">${row.status==='completed'?'Пройдено ✓':'Завершить урок'}</button></div></div>`;
 document.getElementById('saveLessonNotesBtn')?.addEventListener('click',async()=>{const notes=document.getElementById('lessonNotes')?.value||'';const {error}=await window.supabaseClient.from('learning_progress').upsert({user_id:window.currentUser.id,lesson_id:l.id,status:row.status==='completed'?'completed':'started',progress:Math.max(Number(row.progress||10),30),notes,updated_at:new Date().toISOString()});if(error){toast(error.message,true);return;}toast('Конспект сохранён');loadTrainingView();});
 document.getElementById('checkQuizBtn')?.addEventListener('click',async()=>{let correct=0;quiz.forEach((q,i)=>{const picked=document.querySelector(`input[name=\"quiz-${i}\"]:checked`);if(picked&&Number(picked.value)===Number(q.answer))correct++;});const score=Math.round(correct/quiz.length*100);const out=document.getElementById('quizResult');if(out)out.textContent=`Результат: ${correct}/${quiz.length} (${score}%).`;await window.supabaseClient.from('learning_progress').upsert({user_id:window.currentUser.id,lesson_id:l.id,status:score>=70?'completed':'started',progress:score>=70?100:Math.max(Number(row.progress||10),60),quiz_score:score,updated_at:new Date().toISOString()});loadTrainingView();});
 document.getElementById('completeLessonBtn')?.addEventListener('click',async()=>{const notes=document.getElementById('lessonNotes')?.value||'';const {error}=await window.supabaseClient.from('learning_progress').upsert({user_id:window.currentUser.id,lesson_id:l.id,status:'completed',progress:100,notes,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()});if(error){toast(error.message,true);return;}toast('Урок завершён');closeModal();loadTrainingView();});}
function bindTrainingUI(){
  const search=document.getElementById('trainingSearch');
  search?.addEventListener('input',()=>{trainingState.search=search.value.toLowerCase();renderTrainingView()});
}
function formatAdminUserMoney(v,c){return formatCurrencyValue(v,c||'USD',false)}
function formatAdminDate(v){return v?new Intl.DateTimeFormat('ru-RU',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'—';}
function nextQuote(){const q=(DEFAULT_DATA.quotes||[]);if(!q.length)return;let idx=Number(sessionStorage.getItem('tradingDiary_quoteIndex')||0);idx=(idx+1)%q.length;sessionStorage.setItem('tradingDiary_quoteIndex',String(idx));renderQuote(idx);}
function renderQuote(idx){const q=(DEFAULT_DATA.quotes||[])[idx%(DEFAULT_DATA.quotes||[]).length];const box=document.getElementById('dashboardQuote');if(box)box.textContent=q;}
