function localDateKey(dateLike=new Date()){const d=new Date(dateLike);return new Intl.DateTimeFormat('en-CA',{timeZone:state.settings.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
function localParts(dateLike=new Date()){const d=new Date(dateLike);const f=new Intl.DateTimeFormat('en-US',{timeZone:state.settings.timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false});const p=Object.fromEntries(f.formatToParts(d).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return p}
function tradeDate(t){return new Date(`${t.date||localDateKey()}T${t.time||'00:00'}:00`)}
function inRange(t,range){const key=localDateKey(tradeDate(t));const now=new Date();const today=localDateKey(now);if(range==='today')return key===today;const todayD=new Date(today+'T00:00:00');const td=new Date(key+'T00:00:00');if(range==='week'){const day=(todayD.getDay()+6)%7;const start=new Date(todayD);start.setDate(todayD.getDate()-day);return td>=start&&td<=todayD}if(range==='month')return key.slice(0,7)===today.slice(0,7);if(typeof range==='number'){const start=new Date(now.getTime()-range*86400000);return tradeDate(t)>=start}return true}
function stats(trades){const a=trades||[];const wins=a.filter(t=>t.result==='win'),losses=a.filter(t=>t.result==='loss'),draws=a.filter(t=>t.result==='draw');const pnl=round(a.reduce((s,t)=>s+(Number(t.pnl)||0),0));const profit=round(wins.reduce((s,t)=>s+Math.max(0,Number(t.pnl)||0),0));const loss=round(losses.reduce((s,t)=>s+Math.abs(Math.min(0,Number(t.pnl)||0)),0));const winRate=a.length?wins.length/a.length*100:0;const avg=a.length?pnl/a.length:0;const avgPayout=wins.length?wins.reduce((s,t)=>s+Number(t.payout||0),0)/wins.length:0;let maxWin=0,maxLoss=0,w=0,l=0;[...a].sort((x,y)=>tradeDate(x)-tradeDate(y)).forEach(t=>{if(t.result==='win'){w++;l=0}else if(t.result==='loss'){l++;w=0}else{w=0;l=0}maxWin=Math.max(maxWin,w);maxLoss=Math.max(maxLoss,l)});return{trades:a.length,wins:wins.length,losses:losses.length,draws:draws.length,pnl,profit,loss,winRate,avg,avgPayout,maxWin,maxLoss}}
function getPeriodStats(range){return stats(state.trades.filter(t=>inRange(t,range)))}
function formatMoney(v,compact=false){const cur=state.settings.currency;const symbol=(DEFAULT_DATA.currencies.find(c=>c[0]===cur)||[cur,cur])[1];const n=Number(v)||0;return `${n>=0?'+':''}${symbol}${new Intl.NumberFormat('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n)}`}
function formatMoneyPlain(v){const cur=state.settings.currency;const symbol=(DEFAULT_DATA.currencies.find(c=>c[0]===cur)||[cur,cur])[1];return `${symbol}${new Intl.NumberFormat('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v)||0)}`}
function currentBalance(){return round(Number(state.settings.startingBalance||0)+state.trades.reduce((s,t)=>s+Number(t.pnl||0),0))}
function sortedTrades(){return [...state.trades].sort((a,b)=>tradeDate(a)-tradeDate(b))}
function balanceSeries(){let bal=Number(state.settings.startingBalance||0);return sortedTrades().map(t=>{bal=round(bal+Number(t.pnl||0));return{date:tradeDate(t),value:bal,pnl:Number(t.pnl||0),trade:t}})}
function groupByDay(){const map={};sortedTrades().forEach(t=>{const k=t.date||localDateKey(tradeDate(t));if(!map[k])map[k]=[];map[k].push(t)});return Object.entries(map).map(([date,trades])=>({date,trades,...stats(trades)})).sort((a,b)=>a.date.localeCompare(b.date))}
function groupByMonth(){const map={};sortedTrades().forEach(t=>{const k=(t.date||'').slice(0,7);if(!map[k])map[k]=[];map[k].push(t)});return Object.entries(map).map(([date,trades])=>({date,trades,...stats(trades)})).sort((a,b)=>a.date.localeCompare(b.date))}
function groupByWeek(){const map={};sortedTrades().forEach(t=>{const d=new Date((t.date||'')+'T00:00:00');const day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);const k=d.toISOString().slice(0,10);if(!map[k])map[k]=[];map[k].push(t)});return Object.entries(map).map(([date,trades])=>({date,trades,...stats(trades)})).sort((a,b)=>a.date.localeCompare(b.date))}
