const STORAGE_KEY='tradingDiary_v3';
function clone(v){return JSON.parse(JSON.stringify(v))}
function loadState(){const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return clone(DEFAULT_DATA);try{const s=JSON.parse(raw);return {...clone(DEFAULT_DATA),...s,settings:{...clone(DEFAULT_DATA).settings,...(s.settings||{})},mainGoal:{...clone(DEFAULT_DATA).mainGoal,...(s.mainGoal||{})},trades:Array.isArray(s.trades)?s.trades:[],notes:Array.isArray(s.notes)?s.notes:[],plans:Array.isArray(s.plans)?s.plans:[],goals:Array.isArray(s.goals)?s.goals:[],journal:s.journal||{}}}catch{return clone(DEFAULT_DATA)}}
let state=loadState();
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));document.dispatchEvent(new CustomEvent('state:changed'))}
function uid(){return 'id_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8)}
function exportJson(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});downloadBlob(blob,`trading-diary-${new Date().toISOString().slice(0,10)}.json`)}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function csvEscape(v){return `"${String(v??'').replaceAll('"','""')}"`}
function exportCsv(){const headers=['id','date','time','instrument','category','type','expiration','stake','payout','result','pnl','strategy','platform','state','note'];const rows=state.trades.map(t=>headers.map(h=>csvEscape(t[h])).join(','));downloadBlob(new Blob([[headers.join(','),...rows].join('\n')],{type:'text/csv;charset=utf-8'}),`trading-diary-${new Date().toISOString().slice(0,10)}.csv`)}
function parseCsv(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(!lines.length)return[];const parseLine=line=>{let out=[],cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&line[i+1]==='"'){cur+='"';i++;continue}if(c==='"'){q=!q;continue}if(c===','&&!q){out.push(cur);cur='';continue}cur+=c}out.push(cur);return out};const headers=parseLine(lines[0]).map(x=>x.trim().toLowerCase());const aliases={date:['date','дата'],time:['time','время'],instrument:['instrument','asset','symbol','инструмент'],type:['type','direction','тип'],expiration:['expiration','expiry','экспирация'],stake:['stake','amount','investment','ставка','сумма'],payout:['payout','profit percent','payout %','выплата'],result:['result','outcome','результат'],strategy:['strategy','стратегия'],platform:['platform','account','платформа'],state:['state','psychology','состояние'],note:['note','notes','комментарий','заметка']};const idx={};Object.entries(aliases).forEach(([key,list])=>idx[key]=headers.findIndex(h=>list.includes(h)));return lines.slice(1).map(line=>{const vals=parseLine(line);const t={id:uid()};Object.entries(idx).forEach(([k,i])=>{if(i>=0)t[k]=vals[i]||''});t.stake=Number(String(t.stake||0).replace(',','.'))||0;t.payout=Number(String(t.payout||state.settings.defaultPayout).replace(',','.'))||state.settings.defaultPayout;t.result=String(t.result||'draw').toLowerCase();if(['win','profit','won','плюс','выигрыш'].some(x=>t.result.includes(x)))t.result='win';else if(['loss','lost','minus','минус','убыток'].some(x=>t.result.includes(x)))t.result='loss';else t.result='draw';t.pnl=calculatePnl(t);t.category=t.category||findInstrument(t.instrument)?.category||'Custom';t.type=(String(t.type||'CALL').toUpperCase().includes('PUT')?'PUT':'CALL');return t}).filter(t=>t.instrument)}
function calculatePnl(t){const stake=Number(t.stake)||0,payout=Number(t.payout)||0;if(t.result==='win')return round(stake*payout/100);if(t.result==='loss')return round(-stake);return 0}
function round(n){return Math.round((Number(n)||0)*100)/100}
function findInstrument(name){return state.instruments.find(i=>i.name.toLowerCase()===String(name||'').toLowerCase())}
